services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app-network

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network
    restart: on-failure
  
  admin-service:
    build: ./admin-service
    env_file:
      - ./admin-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network
    restart: on-failure
  
  event-service:
    build: ./event-service
    env_file:
      - ./event-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network
    restart: on-failure
  
  message-service:
    build: ./message-service
    env_file:
      - ./message-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
      - USER_SERVICE=http://user-service:5001
    depends_on:
      - kafka
    networks:
      - app-network
    restart: on-failure
  
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/.env
    environment:
      - USER_SERVICE=http://user-service:5001
      - ADMIN_SERVICE=http://admin-service:5002
      - EVENT_SERVICE=http://event-service:5003
      - MESSAGE_SERVICE=http://message-service:5004
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
      - user-service
      - admin-service
      - event-service
      - message-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  kafka_data: