export enum HttpResponse {
    NEED_ORGANIZER_ACCESS = "Forbidden: You don't have organizer access",
    MAX_TICKET_LIMIT = "You have already purchased the maximum limit of tickets",
    OUT_OF_STOCK = "Ticket for the event is currently out of stock",
    BOOKING_INITIATED = "Booking initiated",
    BOOKING_FETCHED = "Booking fetched",
    BOOKING_NOT_FOUND = "Booking not found",
    TICKETS_CANCELLED = "Tickets cancelled",
    NO_BOOKINGS = "No bookings",
    BOOKINGS_FOUND = "Bookings found",
    NOT_PURCHASED = "You have to purchase this event",
    ALL_CANCELLED = "All bookings for the event have been cancelled",
    PAYMENT_FAILED = "Payment Failed",
    COUPON_ELIGIBLE = "Eligibile for applying",
    ALREADY_APPLIED = "You have already applied this coupon",
    PAYMENT_INITIATED = "Payment initiated",
    MISSING_SESSION_ID = "Missing session ID",
    PAYMENT_SUCCESS = "Payment successful",
    WALLET_DOESNT_EXISTS = "Wallet doesn't exist for this user",
    WALLER_FETCHED = "Wallet fetched",
    INSUFFICENT_BALANCE = "Insufficent balance in your wallet",
    EVENT_DOESNT_EXISTS = "Event doesn't exist",
    INTERNAL_SERVER_ERROR = "Internal server error"
}