apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: anandpskerala/api-gateway:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: gateway-env
          env:
            - name: FRONTEND_URL
              value: https://nexevent.appxstore.shop
            - name: USER_SERVICE
              value: http://user-service.default.svc.cluster.local:5001
            - name: ADMIN_SERVICE
              value: http://admin-service.default.svc.cluster.local:5002
            - name: EVENT_SERVICE
              value: http://event-service.default.svc.cluster.local:5003
            - name: MESSAGE_SERVICE
              value: http://message-service.default.svc.cluster.local:5004
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"